### ISSUE TITLE
ssl 'module' object has no attribute 'SSLContext'

### ISSUE THREAD

**Issue by Alonreznik** [PyMySQL/PyMySQL#546]
Hi There and thanks in advanced for everything.
After upgrading our pymysql from 0.6.7 to 0.7.9, we got the problem as above: 
ssl 'module' object has no attribute 'SSLContext'.
It looks like any version after 0.7.0 gets that issue.

Our python is 2.7.3. After some reading it looks like only python>=2.7.9 compatible with the SSLContext attribute. We have pyopenssl on the machine and openssl.

 Is it any chance to use pymysql>=0.7.0 with SSL connection, without getting that issue? 
Can it be handled in your side (like using pyopenssl context as a replacement)?

Thanks again!

**Comment by methane** [comment]
I strongly recommend to use new Python.
System python is maintained for running system application, not your application nor libraries from PyPI.
`/usr/bin/python` may have many bugs fixed in upstream.

I won't pay any my energy and time for supporting such an old Python.
Instead, you should pay your time and energy to build new Python. pythonz and pyenv is good tool for that.
